# redis-chat-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-chat-app
  labels:
    app: redis-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-chat-app
  template:
    metadata:
      labels:
        app: redis-chat-app
    spec:
      containers:
        - name: redis-chat-app
          image: docker.io/anurag772/devzero-redis:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-chat-app-service
spec:
  selector:
    app: redis-chat-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
